services:
  db:
    image: nouchka/sqlite3
    container_name: sqlite3
    volumes:
      - db_data:/app/db

  web:
    build: .
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  db_data:
