# Generated by Django 5.1.1 on 2024-09-09 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_investmentaccount_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinvestmentaccount',
            name='permission_level',
        ),
        migrations.AddField(
            model_name='investmentaccount',
            name='permission_level',
            field=models.CharField(choices=[('view_only', 'View Only'), ('full_access', 'Full Access (CRUD)'), ('post_only', 'Post Transactions Only')], default='view_only', max_length=20),
            preserve_default=False,
        ),
    ]
