# Generated by Django 5.1.1 on 2024-09-13 19:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_userinvestmentaccount_permission_level_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investmentaccount',
            name='users',
        ),
        migrations.RemoveField(
            model_name='investmentaccount',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='account',
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.investmentaccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='user_account',
            field=models.ForeignKey(default=2000, on_delete=django.db.models.deletion.CASCADE, to='accounts.useraccount'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='UserInvestmentAccount',
        ),
        migrations.AddConstraint(
            model_name='useraccount',
            constraint=models.UniqueConstraint(fields=('user', 'account_type'), name='unique_user_account_type'),
        ),
    ]
