# Generated by Django 5.1.1 on 2024-09-15 06:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_investmentaccount_users_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='investmentaccount',
            index=models.Index(fields=['permission_level'], name='accounts_in_permiss_f73240_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user_account'], name='accounts_tr_user_ac_d44512_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['created_at'], name='accounts_tr_created_b2c597_idx'),
        ),
        migrations.AddIndex(
            model_name='useraccount',
            index=models.Index(fields=['user'], name='accounts_us_user_id_539486_idx'),
        ),
        migrations.AddIndex(
            model_name='useraccount',
            index=models.Index(fields=['account_type'], name='accounts_us_account_6a569d_idx'),
        ),
    ]
