# Generated by Django 5.1.1 on 2024-09-15 10:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_investmentaccount_accounts_in_permiss_f73240_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='account_number',
            field=models.CharField(default=12345, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='useraccount',
            index=models.Index(fields=['account_number'], name='accounts_us_account_fbc411_idx'),
        ),
    ]
