name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      # Check out the repository's code

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'
      # Set up Python 3.12 for the environment

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      # Upgrade pip and install dependencies from requirements.txt

    - name: Run tests
      run: |
        python manage.py migrate
        python manage.py test
      # Apply database migrations and run tests
